/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_TestDriver */

#ifndef _Included_app_TestDriver
#define _Included_app_TestDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_TestDriver
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_TestDriver_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     app_TestDriver
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_app_TestDriver_booleanMethod
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
