/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_NativeFunctions */

#ifndef _Included_application_NativeFunctions
#define _Included_application_NativeFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_NativeFunctions
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_application_NativeFunctions_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
