/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestDriver */

#ifndef _Included_TestDriver
#define _Included_TestDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestDriver
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_TestDriver_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     TestDriver
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_TestDriver_booleanMethod
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
